### ISSUE TITLE
Add a background-color to icons

### ISSUE THREAD

**Issue by Florian-R** [ivogabe/Brackets-Icons#35]
Very very minor issue, so feel free to dismiss it.

When used with the [brackets tree extension](https://github.com/lamo2k123/brackets-tree), there's a small glitch where the line is displayed below the icon.

![sample](https://cloud.githubusercontent.com/assets/1374176/4665828/fc077148-554d-11e4-9acb-3821df0ad446.png)

Just adding: 

``` css
//@dark-bc-sidebar-bg
.jstree ins.file-tree-view-icon {
  background-color: #3C3F41;
}

//@dark-bc-sidebar-selection
.jstree-clicked ins.file-tree-view-icon {
  background-color: #2D2E30
}
```

seems to do the trick.

Those colors are grabbed from https://github.com/adobe/brackets/blob/master/src/styles/brackets_core_ui_variables.less but i haven't figured a way to use those variables directly.
